### ISSUE TITLE
Page break at end of a4 page

### ISSUE THREAD

**Issue by JWWright86** [delight-im/HTML-Sheets-of-Paper#2]
Is it possible to have a page break when the user reaches the end of a page? At present the page extends further down when more lines are added

**Comment by ocram** [comment]
Thanks for your feedback!

You are absolutely right. This is definitely an issue. If you look at this in the browser, the pages just expand in height and don't break automatically.

But this should only affect the view in the browser, which is actually a preview mode only. If you switch to the print mode by going to your browser's print dialog for the particular page, everything should be correct, with page breaks as you expect them.

You will, however, see that the text flow is entirely different in the preview mode and in the print mode.

_Maybe_ this is a browser issue, since it's definitely possible to have automatic page breaks, as you can see in the print mode. But _maybe_ it's really an issue that we can fix, probably by adjusting the CSS rules. That would be great!

Anyway, as you could see already, I have no idea yet how to fix this, personally. But we'll leave this issue open until someone finds out :) Sorry that there's no real solution yet. But if you're only interested in printing, this should not be an issue.

**Comment by thgh** [comment]
With javascript, you could move the last paragraph of the page to the next one if the page is longer than expected. Rinse & repeat until all pages fit.

**Comment by ocram** [comment]
@thgh Thanks, that's definitely a simple but effective alternative. However, I'm still hoping for some cleaner and more elegant solution, perhaps using CSS only. I've been experimenting and doing some research, but to no avail, so far.

A clean CSS solution would have another major advantage, namely full congruency between the `screen` and `print` modes, which is highly desirable, I think, at least for "WYSIWYG". At the moment, we should have this property.

Anyway, we might implement a JavaScript solution at least until we find something better (which may never happen). There are some issues that would need to be resolved for a JavaScript solution, of course. Example: When would you update the pages (check if content needs to be moved to the next page)? On every key press? After some delay, i.e. debounced? Wouldn't that cause the content to "jump" every few seconds during writing when there is an update?

**Comment by thgh** [comment]
Whatever happens in Word is what I expect to happen here. I guess onkeypress and throttled at 300ms.

Splitting paragraphs over multiple pages might be challenging. I would probably add some class to the splitted parts which tells the renderer that these parts should be combined. The tricky part is then to find the last word that fits on the page.

There should be some html to pdf spec that outlines how it should layout the page.

**Comment by zaid0786** [comment]
this will be lit a bit help for you all
@media print {
 div,table,html{-webkit-region-break-inside: avoid;}
   table { page-break-inside:auto }
    tr    { page-break-inside:avoid; page-break-after:auto }
    thead { display:table-header-group }
    tfoot { display:table-footer-group }
}

**Comment by ocram** [comment]
@zaid0786 Thanks! Can you explain what this does exactly? The best thing would be two screenshots for comparison, one *before* and one *after* applying that modification.

**Comment by zicklag** [comment]
I have yet to try it for my project, but this project might be exactly what we need here:

https://github.com/pagedjs/pagedjs

**Comment by ocram** [comment]
While I had hoped for a more elegant solution, and perhaps for better CSS Paged Media support in browsers outside of `print` mode, the simple JavaScript solution we have been using over the years has now been integrated in https://github.com/delight-im/HTML-Sheets-of-Paper/commit/c16be57fe0ca29ddec5dda62867048f86645434b and https://github.com/delight-im/HTML-Sheets-of-Paper/commit/3cb8d94ce1ed8520bd3524c6c8829cc592acb0cf.

It does only work on headings and paragraphs as a whole, so no splitting *within* a paragraph yet. Perhaps this can be improved in the future. But this is probably best discussed in a separate issue per specific aspect or idea.
