### ISSUE TITLE
Is the demo 2 pages or 3?

### ISSUE THREAD

**Issue by s1037989** [delight-im/HTML-Sheets-of-Paper#5]
I'm seeing two pages, but in the middle of the first page, it says "This sentence is preceded by a manual page break."  Yet there is no page break.  Should there be three pages?

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/76.0.3809.87 Chrome/76.0.3809.87 Safari/537.36

![Selection_999(523)](https://user-images.githubusercontent.com/517498/65765719-a5340980-e0ee-11e9-85ce-4345aa9737a9.png)

**Comment by ocram** [comment]
Sorry for the long delay, and yes, you are correct!

Just as [this other issue](https://github.com/delight-im/HTML-Sheets-of-Paper/issues/2), this is a problem with the default preview mode (i.e. `screen`).

If you switch to `print` by going to your browser's print dialog for the particular page, it should work.

But this is not enough, of course. We’d love to fix the behavior to work correctly in both modes.

By the way, there’s a typo. It should really say “This sentence is preceded by a manual page break” (instead of “line break”), as you already said.

**Comment by ocram** [comment]
The typo has been fixed [here](https://github.com/delight-im/HTML-Sheets-of-Paper/commit/b50e48cf7a82300a4c20f6de7fa546f00d36675d) and manual line breaks are now simulated in `screen` mode, as implemented [here](https://github.com/delight-im/HTML-Sheets-of-Paper/commit/a14900ba86cdc8b08445bd01f04bd0970229c2ed), so that the `print` and `screen` modes don’t differ that much. The remaining (open) questions are still tracked in the other issue.
