### ISSUE TITLE
dynamic content

### ISSUE THREAD

**Issue by alexsoft12** [delight-im/HTML-Sheets-of-Paper#7]
What if we have dynamic content which may be unto 3-4 or more pages?

**Comment by ocram** [comment]
Thanks!

What exactly is your problem with dynamic content?

Are you concerned about (automatic) page breaks? Is this other issue helpful perhaps? https://github.com/delight-im/HTML-Sheets-of-Paper/issues/2

**Comment by frozenade** [comment]
Hi
I found this method is works but still not the best. https://jsfiddle.net/tk8rwnav/31/
It can break the page dynamically but there's a lot of space at bottom of page when the last paragraph of current page has many text.

Can you fix it?

**Comment by ocram** [comment]
Thanks, @frozenade!

That solution, using JavaScript to dynamically move content around (to new page containers), is close to the workaround that was mentioned in the issue linked above and that we have been using over the years.

It seems your solution is based on `scrollHeight` to determine if there is any invisible content that is hidden (overflow). That’s not what we did, but it’s the same direction.

We have integrated our solution into this repository here now.

Apart from that, let’s keep the discussion in the other issue, since this here seems to be a duplicate.
